version: '3.8'

services:
  oi-sandbox:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./workspace:/app/workspace
      - ./chats.db:/app/chats.db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - API_BASE=${API_BASE:-}
      - AZURE_ENDPOINT=${AZURE_ENDPOINT:-}
      - API_VERSION=${API_VERSION:-}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
